var dog_api = 'https://dog.ceo/api/'
var breed = 'breed/'
var breeds = 'breeds/'
var random_image = 'image/random'
var random_images = 'images/randon'
var list = 'list'
var images = 'images'
var catalog = 'catalog'
